# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAutocommit < Formula
  desc "AI-powered automatic git commit message generator"
  homepage "https://github.com/webbcam/git-autocommit"
  version "0.3.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/webbcam/git-autocommit/releases/download/v0.3.0/git-autocommit_0.3.0_darwin_amd64.tar.gz"
    sha256 "662f450e57d90b62fb09a3612476264fdad8380bd33fe3b6009fba08f9956b08"

    define_method(:install) do
      bin.install "git-autocommit"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/webbcam/git-autocommit/releases/download/v0.3.0/git-autocommit_0.3.0_darwin_arm64.tar.gz"
    sha256 "8c3b70862336a5e57c971b85b220725330323ef43d28dd795d58d788ddaf0ce0"

    define_method(:install) do
      bin.install "git-autocommit"
    end
  end
end
