# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Parcel < Formula
  desc "CLI tool for tracking parcels and packages"
  homepage "https://github.com/webbcam/parcel"
  version "0.1.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/webbcam/parcel/releases/download/v0.1.0/parcel_0.1.0_darwin_amd64.tar.gz"
    sha256 "8c270de902f4047abfa4529867427760fd88dac42469e15538155cf4e3388b1b"

    define_method(:install) do
      bin.install "parcel"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/webbcam/parcel/releases/download/v0.1.0/parcel_0.1.0_darwin_arm64.tar.gz"
    sha256 "38597ac9be784cf5787d7bc839f7d28298edbe500d3556fa5216fba9aa06d63a"

    define_method(:install) do
      bin.install "parcel"
    end
  end
end
